---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-service"
  namespace: "hello"
spec:
  type: "ClusterIP"
  selector:
    component: "web"
  ports:
    - port: 80
      targetPort: 8080
...
