Vagrant.configure("2") do |config|

  # libvirt
  config.vm.provider "libvirt" do |lv|
    lv.cpus = 4
    lv.memory = 4096
  end

  # virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 4096
    vb.linked_clone = true
  end

  # provision
  config.vm.provision "ansible" do |site|
    site.playbook = "site.yml"
  end

  # machine
  config.vm.define "edge01" do |edge01|
    edge01.vm.box = "fedora/33-cloud-base"
    edge01.vm.hostname = "edge01"
  end

end
